### ISSUE TITLE
[web] Implementar env customizado para o footer da homepage

### ISSUE THREAD

**Issue by alessandrofeitoza** [ecossistema-aurora/aurora#181]
## WHAT
Atualmente o footer maior (homepage) ainda mostra opções não existentes quando configuramos de forma diferente o tema.

## CHECKLIST
- [ ] O footer deveria mostrar apenas os módulos habilitados.

## SCENARIO
Adicionar o conteudo abaixo dentro de `/config/envinronment/aurora.local.yaml`

```yaml
name: Mapa das Periferias
author: Secretaria Nacional de Periferias
logo:
  horizontal:
    path: https://www.gov.br/cidades/pt-br/acesso-a-informacao/acoes-e-programas/periferias/mapa-das-periferias/@@images/c2b71df1-508b-4c56-b863-9527afc9bad8.png
    width: 70px
  vertical:
    path: https://www.gov.br/cidades/pt-br/acesso-a-informacao/acoes-e-programas/periferias/mapa-das-periferias/@@images/c2b71df1-508b-4c56-b863-9527afc9bad8.png
    width: 70px
modules:
  organizations: Municipios
  agents: Promotores
  opportunities: Credenciamento
  events:
  spaces:
  initiatives:
homepage:
  sections:
    header:
      enabled: true
      title: Mapa das Periferias
      subtitle: subtitulo aqui
      description: descricao aqui
      background: bg-dark
      image: img/regmel.png
    register:
      enabled: false
    opportunities:
      enabled: false
    modules:
      enabled: true
    happen_now:
      enabled: false
    maps:
      enabled: true
      background: bg-dark
      color: text-light
    contribute:
      enabled: false
```
